language: rust

matrix:
  include:
    - env: TARGET=NATIVE_BETA
      rust: beta
    # Note: apt packages are the C cross compiler and the cross compiled C library
    - env: TARGET=arm-unknown-linux-gnueabi
      addons:
        apt:
          packages:
            - gcc-arm-linux-gnueabi
            - libc6-armel-cross
            - libc6-dev-armel-cross
    - env: TARGET=arm-unknown-linux-gnueabihf
      addons:
        apt:
          packages: &armhf
            - gcc-arm-linux-gnueabihf
            - libc6-armhf-cross
            - libc6-dev-armhf-cross
    - env: TARGET=armv7-unknown-linux-gnueabihf
      addons:
        apt:
          packages: *armhf
    - env: TARGET=i686-unknown-linux-gnu
      addons:
        apt:
          packages: *i686
    - env: TARGET=x86_64-unknown-linux-musl
    - env: TARGET=x86_64-pc-windows-gnu
      dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - gcc-mingw-w64

install:
  - if [[ $TARGET != NATIVE* ]]; then export PATH="$PATH:$HOME/.cargo/bin" && curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain=beta && rustup target add $TARGET; fi
  - rustc -V
  - cargo -V

script:
  - if [[ $TARGET != NATIVE* ]]; then cargo build --target $TARGET; fi
  - if [[ $TARGET = NATIVE* ]]; then cargo build && cargo test; fi
